export type LangItem = { key: string; label: string };

// ISO 639-1 full list (184 languages)
const ALL_LANGUAGES: LangItem[] = [
  { key: "aa", label: "Afar" },
  { key: "ab", label: "Abkhazian" },
  { key: "af", label: "Afrikaans" },
  { key: "ak", label: "Akan" },
  { key: "am", label: "Amharic" },
  { key: "an", label: "Aragonese" },
  { key: "ar", label: "Arabic" },
  { key: "as", label: "Assamese" },
  { key: "av", label: "Avaric" },
  { key: "ay", label: "Aymara" },
  { key: "az", label: "Azerbaijani" },
  { key: "ba", label: "Bashkir" },
  { key: "be", label: "Belarusian" },
  { key: "bg", label: "Bulgarian" },
  { key: "bh", label: "Bihari" },
  { key: "bi", label: "Bislama" },
  { key: "bm", label: "Bambara" },
  { key: "bn", label: "Bengali" },
  { key: "bo", label: "Tibetan" },
  { key: "br", label: "Breton" },
  { key: "bs", label: "Bosnian" },
  { key: "ca", label: "Catalan" },
  { key: "ce", label: "Chechen" },
  { key: "ch", label: "Chamorro" },
  { key: "co", label: "Corsican" },
  { key: "cr", label: "Cree" },
  { key: "cs", label: "Czech" },
  { key: "cu", label: "Church Slavic" },
  { key: "cv", label: "Chuvash" },
  { key: "cy", label: "Welsh" },
  { key: "da", label: "Danish" },
  { key: "de", label: "German" },
  { key: "dv", label: "Divehi" },
  { key: "dz", label: "Dzongkha" },
  { key: "ee", label: "Ewe" },
  { key: "el", label: "Greek" },
  { key: "en", label: "English" },
  { key: "eo", label: "Esperanto" },
  { key: "es", label: "Spanish" },
  { key: "et", label: "Estonian" },
  { key: "eu", label: "Basque" },
  { key: "fa", label: "Persian" },
  { key: "ff", label: "Fulah" },
  { key: "fi", label: "Finnish" },
  { key: "fj", label: "Fijian" },
  { key: "fo", label: "Faroese" },
  { key: "fr", label: "French" },
  { key: "fy", label: "Western Frisian" },
  { key: "ga", label: "Irish" },
  { key: "gd", label: "Scottish Gaelic" },
  { key: "gl", label: "Galician" },
  { key: "gn", label: "Guarani" },
  { key: "gu", label: "Gujarati" },
  { key: "gv", label: "Manx" },
  { key: "ha", label: "Hausa" },
  { key: "he", label: "Hebrew" },
  { key: "hi", label: "Hindi" },
  { key: "ho", label: "Hiri Motu" },
  { key: "hr", label: "Croatian" },
  { key: "ht", label: "Haitian Creole" },
  { key: "hu", label: "Hungarian" },
  { key: "hy", label: "Armenian" },
  { key: "hz", label: "Herero" },
  { key: "ia", label: "Interlingua" },
  { key: "id", label: "Indonesian" },
  { key: "ie", label: "Interlingue" },
  { key: "ig", label: "Igbo" },
  { key: "ii", label: "Sichuan Yi" },
  { key: "ik", label: "Inupiaq" },
  { key: "io", label: "Ido" },
  { key: "is", label: "Icelandic" },
  { key: "it", label: "Italian" },
  { key: "iu", label: "Inuktitut" },
  { key: "ja", label: "Japanese" },
  { key: "jv", label: "Javanese" },
  { key: "ka", label: "Georgian" },
  { key: "kg", label: "Kongo" },
  { key: "ki", label: "Kikuyu" },
  { key: "kj", label: "Kuanyama" },
  { key: "kk", label: "Kazakh" },
  { key: "kl", label: "Kalaallisut" },
  { key: "km", label: "Khmer" },
  { key: "kn", label: "Kannada" },
  { key: "ko", label: "Korean" },
  { key: "kr", label: "Kanuri" },
  { key: "ks", label: "Kashmiri" },
  { key: "ku", label: "Kurdish" },
  { key: "kv", label: "Komi" },
  { key: "kw", label: "Cornish" },
  { key: "ky", label: "Kyrgyz" },
  { key: "la", label: "Latin" },
  { key: "lb", label: "Luxembourgish" },
  { key: "lg", label: "Ganda" },
  { key: "li", label: "Limburgish" },
  { key: "ln", label: "Lingala" },
  { key: "lo", label: "Lao" },
  { key: "lt", label: "Lithuanian" },
  { key: "lu", label: "Luba-Katanga" },
  { key: "lv", label: "Latvian" },
  { key: "mg", label: "Malagasy" },
  { key: "mh", label: "Marshallese" },
  { key: "mi", label: "Maori" },
  { key: "mk", label: "Macedonian" },
  { key: "ml", label: "Malayalam" },
  { key: "mn", label: "Mongolian" },
  { key: "mr", label: "Marathi" },
  { key: "ms", label: "Malay" },
  { key: "mt", label: "Maltese" },
  { key: "my", label: "Burmese" },
  { key: "na", label: "Nauru" },
  { key: "nb", label: "Norwegian Bokmål" },
  { key: "nd", label: "North Ndebele" },
  { key: "ne", label: "Nepali" },
  { key: "ng", label: "Ndonga" },
  { key: "nl", label: "Dutch" },
  { key: "nn", label: "Norwegian Nynorsk" },
  { key: "no", label: "Norwegian" },
  { key: "nr", label: "South Ndebele" },
  { key: "nv", label: "Navajo" },
  { key: "ny", label: "Chichewa" },
  { key: "oc", label: "Occitan" },
  { key: "oj", label: "Ojibwa" },
  { key: "om", label: "Oromo" },
  { key: "or", label: "Odia" },
  { key: "os", label: "Ossetian" },
  { key: "pa", label: "Punjabi" },
  { key: "pi", label: "Pali" },
  { key: "pl", label: "Polish" },
  { key: "ps", label: "Pashto" },
  { key: "pt", label: "Portuguese" },
  { key: "qu", label: "Quechua" },
  { key: "rm", label: "Romansh" },
  { key: "rn", label: "Rundi" },
  { key: "ro", label: "Romanian" },
  { key: "ru", label: "Russian" },
  { key: "rw", label: "Kinyarwanda" },
  { key: "sa", label: "Sanskrit" },
  { key: "sc", label: "Sardinian" },
  { key: "sd", label: "Sindhi" },
  { key: "se", label: "Northern Sami" },
  { key: "sg", label: "Sango" },
  { key: "si", label: "Sinhala" },
  { key: "sk", label: "Slovak" },
  { key: "sl", label: "Slovenian" },
  { key: "sm", label: "Samoan" },
  { key: "sn", label: "Shona" },
  { key: "so", label: "Somali" },
  { key: "sq", label: "Albanian" },
  { key: "sr", label: "Serbian" },
  { key: "ss", label: "Swati" },
  { key: "st", label: "Southern Sotho" },
  { key: "su", label: "Sundanese" },
  { key: "sv", label: "Swedish" },
  { key: "sw", label: "Swahili" },
  { key: "ta", label: "Tamil" },
  { key: "te", label: "Telugu" },
  { key: "tg", label: "Tajik" },
  { key: "th", label: "Thai" },
  { key: "ti", label: "Tigrinya" },
  { key: "tk", label: "Turkmen" },
  { key: "tl", label: "Filipino" },
  { key: "tn", label: "Tswana" },
  { key: "to", label: "Tonga" },
  { key: "tr", label: "Turkish" },
  { key: "ts", label: "Tsonga" },
  { key: "tt", label: "Tatar" },
  { key: "tw", label: "Twi" },
  { key: "ty", label: "Tahitian" },
  { key: "ug", label: "Uyghur" },
  { key: "uk", label: "Ukrainian" },
  { key: "ur", label: "Urdu" },
  { key: "uz", label: "Uzbek" },
  { key: "ve", label: "Venda" },
  { key: "vi", label: "Vietnamese" },
  { key: "vo", label: "Volapük" },
  { key: "wa", label: "Walloon" },
  { key: "wo", label: "Wolof" },
  { key: "xh", label: "Xhosa" },
  { key: "yi", label: "Yiddish" },
  { key: "yo", label: "Yoruba" },
  { key: "za", label: "Zhuang" },
  { key: "zh", label: "Chinese" },
  { key: "zu", label: "Zulu" },
];

export function getAllLanguages(): LangItem[] {
  return ALL_LANGUAGES;
}

export function langLabel(key: string): string {
  return ALL_LANGUAGES.find((l) => l.key === key)?.label ?? key;
}
